### ISSUE TITLE
Experiment runtime value does not match reported value in the workers page

### ISSUE THREAD

**Issue by H4dr1en** [allegroai/clearml-server#100]
Hi, 

Following up the following Slack thread: https://clearml.slack.com/archives/CTK20V944/p1639659938028700

I think there is a small bug in the Experiment running time column of the workers-and-queues/workers page: they do not match the time reported in the experiment > INFO > Runtime value. 

Eg. I see `14h 27m21s` in the workers page and `08:22:26m` in the info tab of the experiment

**Comment by jkhenning** [comment]
Closing this as it was already fixed in released versions. Please reopen if required.
