### ISSUE TITLE
GCP Custom Image for `v1.2.0`

### ISSUE THREAD

**Issue by mmiller-max** [allegroai/clearml-server#109]
I can't find a GCP custom image for the latest version, and the [docs](https://clear.ml/docs/latest/docs/deploying_clearml/clearml_server_gcp#clearml-server-gcp-custom-image) seem out of date - they still point to `v1.0.2`. 

Is it possible for a custom image to be released for `v1.2.0`? Cheers

EDIT: looking forward to trying out the new server!

**Comment by ainoam** [comment]
@mmiller-max GCP Images are being worked on... Stay tuned.

**Comment by mmiller-max** [comment]
Great to hear! Is there a rough timeframe (just to help with planning)?

**Comment by ainoam** [comment]
@mmiller-max Should be a matter of a day or two.

**Comment by mmiller-max** [comment]
Great, thank you!
