### ISSUE TITLE
Artifacts not being deleted when deleting task

### ISSUE THREAD

**Issue by mmiller-max** [allegroai/clearml-server#112]
When I delete a task using the Web GUI, I see the following message:
<img width="422" alt="Screenshot 2022-02-24 at 09 51 15" src="https://user-images.githubusercontent.com/59854849/155500635-6e99d86b-583b-459d-a329-75b289d9f9fb.png">

When I check the fileserver in the VM on which it's running, I can see that the artifacts are still there, for example at the location `/opt/clearml/data/fileserver/project/task/artifacts/...`

So there seems to be two issues, one with artifacts not being deleted (which I wasn't aware happened with previous version of server) and one with the error message not showing what hasn't been deleted.

Server version is `1.2.0` running on GCP. Cheers!

**Comment by jkhenning** [comment]
Hi @mmiller-max ,

Any more info? Is this reproducible? If so, can you share a small code snippet that creates a task which exhibits this behavior when deleted using the UI?

**Comment by jkhenning** [comment]
Well, seems like an obvious but - we'll take a look, I'll update!

**Comment by mmiller-max** [comment]
Cheers @jkhenning !

**Comment by mmiller-max** [comment]
Trying to do a bit of debugging on this but can't see anything in the fileserver logs. Do I need to set something in `logging.conf` in either the file server or the api server?

**Comment by jkhenning** [comment]
I think you should see console logs. The issue might be in the WebApp...

**Comment by mmiller-max** [comment]
I think this is the corresponding wb app log but can't see any errors with it:
```
35.191.10.5 - - [29/Mar/2022:13:52:30 +0000] "POST /api/v2.16/tasks.delete_many HTTP/1.1" 200 395 "https://app.{domain}/projects/c28adf12db964d169a645f5351a669de/experiments?columns=selected&columns=type&columns=name&columns=tags&columns=status&columns=project.name&columns=users&columns=started&columns=last_update&columns=last_iteration&columns=parent.name&order=-last_update&filter=&archive=true" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.2 Safari/605.1.15" "195.224.76.82,34.149.227.91"
```

**Comment by mmiller-max** [comment]
This seems to be cropping up often in slack, e.g. [here](https://clearml.slack.com/archives/CTK20V944/p1650466643911469), [here](https://clearml.slack.com/archives/CTK20V944/p1649936841850489) and [here](https://clearml.slack.com/archives/CTK20V944/p1648547056095859). It seems to be agnostic of whether the files are stored on the same VM as the server or elsewhere, and seems to be an issue in the Web App as there are no logs in the fileserver.

**Comment by mmiller-max** [comment]
One further comment, I'm pretty sure I never saw this error with ClearML Server v1.1.1

**Comment by mmiller-max** [comment]
After updating to the latest server (1.9.1) I'm no longer seeing these errors so going to close this 👏

**Comment by ainoam** [comment]
Appreciate the update @mmiller-max
