### ISSUE TITLE
Unable to restore backup / backup not loaded

### ISSUE THREAD

**Issue by horefice** [allegroai/clearml-server#118]
Hi there,

I've tried to restore a backup after a clean install and the data doesn't appear in clearml. The last version we had is probably from late last year and now we have it updated. I've also noticed a warning regarding empty elasticsearch password when starting the docker compose. Any ideas on how to proceed?

Best regards

**Comment by jkhenning** [comment]
Hi @horefice,

What was the server version from which you did the backup? there were two releases over the past two years that required migration, and I suspect that's the issue you're facing now.

**Comment by invoxiaehu** [comment]
Hello, we have the same symptom ( backup data not loaded), and it seems to come from Mongo version which bumped from 3.* to 4.*.
In the previous version mongo data was in /opt/clearml/data/mongo/
And now it's in /opt/clearml/data/mongo_4/
I guess a migration is needed.
Any tutorial, or migration script available ?

Thanx

**Comment by jkhenning** [comment]
Hi @invoxiaehu ,

See [Upgrading Server from v1.1 or Older](https://clear.ml/docs/latest/docs/deploying_clearml/clearml_server_mongo44_migration) 🙂

**Comment by horefice** [comment]
I also missed the migration, thank you for the help!

By any chance, is there an easy way to merge the newly initialized mongo_4 (without migration) and the migrated one? I had some experiments that needed to be run asap on the fresh new mongo_4 so now I have two folders with usefull experiments.

**Comment by jkhenning** [comment]
Hi @horefice ,

> is there an easy way to merge the newly initialized mongo_4 (without migration) and the migrated one?
While possible, it will be a totally manual process. You'll need to export the documents from the "new" mongodb `backend.task` collection, modify the `user` and `company` fields to match a valid user and company in the previous DB and import them to the `backend.task` collection in the previous DB. You'll also need to handle any reference to model IDs (or move them as well, in the same manner)

**Comment by horefice** [comment]
Thank you @jkhenning! I will try it, and anyway, I think this issue should be closed.
