### ISSUE TITLE
users mng for server admin

### ISSUE THREAD

**Issue by Dancho80** [allegroai/clearml-server#125]
is there an option to retrieve a list of all users? for example, server admin could notify all users about a coming downtime/upgrade? 
do you have any plans to enable:
1. admin dashboard for users/groups/permissions mng
2. enable LDAP/SAML SSO authentication

**Comment by erezalg** [comment]
Hi @Dancho80 , 

As for the 2 feature you've requested, they are a part of our enterprise offering. 
You can visit our [pricing](https://clear.ml/pricing/) page to learn more and contact us if you need further information!

**Comment by jkhenning** [comment]
Hi @Dancho80,

> is there an option to retrieve a list of all users? for example, server admin could notify all users about a coming 

Are you referring to user names? emails?

**Comment by jkhenning** [comment]
You can use the `/users.get_all` endpoint to obtains some of the details (emails are currently not visible in the open source version)

**Comment by Dancho80** [comment]
do you have a procedure to migrate users and data to another server? for example creating a replica of the server. Having exactly the same data on another server.
I migrated both folders: 
/opt/clearml/data
/opt/clearml/config

and while deploying a new server, get an error and a dashboard in not displayed well: 
`[clearml.service_repo] Returned 400 for users.get_current_user in 10ms, msg=Invalid user (failed loading user)`

**Comment by jkhenning** [comment]
@Dancho80 I think the migration was done correctly - the error you're receiving is probably due to the browser using an a cookie from the other server - I would suggest deleting cookies and trying again.

**Comment by Dancho80** [comment]
thanks for your support!
