### ISSUE TITLE
Smoothing doesn't work in scalars in version v1.3.0

### ISSUE THREAD

**Issue by zenpoy** [allegroai/clearml-server#127]
Smoothing doesn't seem to have any effect on scalar graphs after upgrade to version 1.3.0.

![image](https://user-images.githubusercontent.com/1201781/160357430-90e7e6e5-7b33-4290-a6fa-53bfa3ff5124.png)

v1.3.0

**Comment by ainoam** [comment]
Thanks for the report @zenpoy.
We'll let you know when a fix is available.

**Comment by jkhenning** [comment]
Closing this as it was already fixed in released versions. Please reopen if required.
