### ISSUE TITLE
[UI] Debug samples view resets when running experiment updates metrics

### ISSUE THREAD

**Issue by mctigger** [allegroai/clearml-server#136]
With the latest clearml-server if you go to Detail View -> Results -> Debug Samples -> Change Metric to anything,  and then press the refresh button/wait for auto refresh you get a blank debug sample page. This seems to happen when metrics are updated.

Slack thread: https://clearml.slack.com/archives/CTK20V944/p1651237370890969

**Comment by ainoam** [comment]
@mctigger Thanks for the report. This should be fixed in the next server release.

**Comment by jkhenning** [comment]
Closing this as it was already fixed in released versions. Please reopen if required.
