### ISSUE TITLE
"Fetch Experiments failed" when typing regex pattern in search bar

### ISSUE THREAD

**Issue by idantene** [allegroai/clearml-server#138]
When typing any regex pattern that contains parentheses in the search bar, the "Fetch Experiments failed" pop-up continuously pops up and interferes with typing the search pattern.
It should probably just highlight the invalid regex pattern instead..?

Steps to reproduce:
1. Toggle the regex option in the search bar
2. Type a pattern that exceeds the minimum requirements and include a parenthesis (`(`, `[`, `)`, or `]`) in the pattern, such that the pattern is not complete yet
3. Be stopped by said pop up :(
4. Click "OK" and try to type some more stuff as you finish the pattern, and get the pop up again, consistently, until the pattern is valid :(

**Comment by ainoam** [comment]
Thanks for the report @idantene.
We'll update when we have a fix available.

**Comment by ainoam** [comment]
@idantene Would changing the notification from a blocking popup to a less intrusive sliding toast provide a good enough first-step workaround in lieu of specific pattern highlight?

**Comment by idantene** [comment]
@ainoam Sure, anything that won't prevent the user from typing the pattern as they go along is helpful.
@bmartinn Suggested simply waiting until the user presses the ENTER key, for example.

**Comment by pollfly** [comment]
Hey @idantene! Just letting you know that this issue has been resolved in the recently released [v1.6.0](https://github.com/allegroai/clearml-server/releases/tag/v1.6.0). Let us know if there are any issues :)

**Comment by idantene** [comment]
Thanks! Indeed fixed :D
