### ISSUE TITLE
How to use restful api to invoke clearml  in java project?

### ISSUE THREAD

**Issue by mullerhai** [allegroai/clearml-server#145]
Hi ,I want to invoke clearml in java project like python ,like  upload model file  upload model weights ,get model train information, I want to use restful api, but  I do not know the api invoke route for clearml ,where to find the clearml server api route list document. thank

**Comment by ainoam** [comment]
@mullerhai https://clear.ml/docs/latest/docs/references/api/index documents ClearML's REST API - Is this what you are looking for?

**Comment by mullerhai** [comment]
> https://clear.ml/docs/latest/docs/references/api/index

yeah  ，thank you ，just what I look for !!!
