### ISSUE TITLE
[Bug] WebUI automatically exits archive

### ISSUE THREAD

**Issue by idantene** [allegroai/clearml-server#148]
Steps to reproduce:
1. Open any project
2. Go to archive
3. Select an archived task
4. Switch to detailed mode (😮‍💨 for still having to do this, viva-la-#134)
5. Select e.g. Configuration tab
TADA. The WebUI automatically flicks back to the non-archived view.

**Comment by pollfly** [comment]
Hey @idantene! Just letting you know that this issue has been resolved in the recently released [v1.7.0](https://github.com/allegroai/clearml-server/releases/tag/v1.7.0). Let us know if there are any issues :)

**Comment by idantene** [comment]
Thanks! Indeed fixed.
