### ISSUE TITLE
ClearML dataset versioning/management performance

### ISSUE THREAD

**Issue by senysenyseny16** [allegroai/clearml-server#155]
hi!

At this moment in our company we use DVC for dataset versioning/management and we want to integrate in our workflow ClearML, so there are two options:
1. Leave DVC for dataset versioning and use ClearML for tracking
2. Set up ClearML for both

The second options looks better, but we couldn't find any information about ClearML dataset versioning performance in comparison to DVC (for example caching speed, support for large datasets, is it based on git?).

Could you clarify this?

Thanks in advance.

**Comment by bmartinn** [comment]
(Duplicate of [clearml#750](https://github.com/allegroai/clearml/issues/750))
Dateset versioning is implemented & fully supported, following the discussion in the original thread
