### ISSUE TITLE
[UI] Allow resizing the name column in a task

### ISSUE THREAD

**Issue by idantene** [allegroai/clearml-server#160]
We like to have verbose file names (= artifact names), but when viewing them in the WebUI, this becomes a bit of a nuisance.
Could you make it so this split is resizable?

![image](https://user-images.githubusercontent.com/12184618/190180420-a1d5ed10-bfec-43a4-90c9-c98050b58e2f.png)

**Comment by ainoam** [comment]
Thanks for the suggestion @idantene - We'll try to fit this into an upcoming release.

**Comment by pollfly** [comment]
Hey @idantene! [v1.11.0](https://github.com/allegroai/clearml-server/releases/tag/v1.11.0) is now out with dynamic side panel width in UI experiment artifacts and configuration.

**Comment by jkhenning** [comment]
@idantene closing this. Please reopen if required.
