### ISSUE TITLE
[UI] weird label on hover

### ISSUE THREAD

**Issue by tomer-grin** [allegroai/clearml-server#163]
Hey,
Got this weird `ellipsis` suffix.
<img width="179" alt="image" src="https://user-images.githubusercontent.com/83909894/191763505-9a3bf609-b569-4943-8bf1-2bf6f33c1ae3.png">
<img width="139" alt="image" src="https://user-images.githubusercontent.com/83909894/191764098-bf4ec0d2-33a7-4b0b-9ac9-fd2535de1c5b.png">

Same for all labels.

Private hosted through ClearML.
WebApp: 3.13.0-594 • Server: 3.13.0-832 • API: 2.21

**Comment by ainoam** [comment]
@tomer-grin Seeing as this is an issue with a commercially hosted server rather than the open source version, this might not be the right place for it?
