### ISSUE TITLE
ClearML server dashboard only display Recent Projects"

### ISSUE THREAD

**Issue by tsangz189** [allegroai/clearml-server#164]
After following tutorials to [deploy clearml server](https://clear.ml/docs/latest/docs/deploying_clearml/clearml_server_linux_mac/#deploying), I encountered this problem. Please take a look at the image below

![Screen Shot 2022-10-24 at 14 41 08](https://user-images.githubusercontent.com/23276580/197463352-96111daa-564f-4014-9a6d-ef299c7f53db.png)

The containers are up and running:
![Screen Shot 2022-10-24 at 14 41 29](https://user-images.githubusercontent.com/23276580/197463411-9f96060e-58d2-4b29-b4ce-6c4f6d052410.png)

My OS is Ubuntu 20.04, docker and docker-compose are the newest version
Docker: Docker version 20.10.20, build 9fdeb9c
Docker compose: docker-compose version 1.24.1, build 4667896b

**What I want**

![Screen Shot 2022-10-24 at 14 56 26](https://user-images.githubusercontent.com/23276580/197465995-e437f520-d58c-4c7b-98ac-95b713de5803.png)

**Comment by NatanMog** [comment]
Hi @tsangz189 , can you try going to the login page directly and login? I think this might be some cookie issue. If it's hosted on your local machine it would look something like this: localhost:8080/login

**Comment by tsangz189** [comment]
@NatanMog It was fixed by clear browser cookies, I haven't tried relogin
