### ISSUE TITLE
Bug in graphs of the comparison of scalars

### ISSUE THREAD

**Issue by H4dr1en** [allegroai/clearml-server#166]
Following up on https://clearml.slack.com/archives/CTK20V944/p1670939388868279:

I just updated clearml-server to 1.8.0 and I see the following in the comparison of Scalars:
![image](https://user-images.githubusercontent.com/16240134/207387341-741fd73c-059c-49da-954e-42a2ba946a67.png)

All the graphs are compressed to the left when the experiment name is too long in the legend.
I am sure it is because of the experiment name in the legend, because when I click on hide legend in the tool bar above the graph, the graph is resized correctly

**Comment by ainoam** [comment]
Thanks for reporting @H4dr1en.

We'll update when a fix is available.

**Comment by pollfly** [comment]
Hey @H4dr1en! Just letting you know that this issue has been resolved in [v.1.9.0](https://github.com/allegroai/clearml-server/releases/tag/v1.9.0). Let us know if there are any issues :)
