### ISSUE TITLE
[bug] Incorrect default project when cloning experiment

### ISSUE THREAD

**Issue by astralai** [allegroai/clearml-server#171]
After updating from 1.8.0 to 1.9.1, whenever I clone an experiment, the default project for the draft copy is the first project in the list instead of the current project

[Slack thread with details](https://clearml.slack.com/archives/CTK20V944/p1673600487126289)

**Comment by ainoam** [comment]
Thanks for reporting @astralai!
A fix should be coming in the next release.

**Comment by pollfly** [comment]
Hey @astralai! Just letting you know that this issue has been resolved in the recently released [v1.9.2](https://github.com/allegroai/clearml-server/releases/tag/v1.9.2). Let us know if there are any issues :)
