### ISSUE TITLE
Other devices in the LAN cannot access clearml server through port 8080

### ISSUE THREAD

**Issue by chakloong883** [allegroai/clearml-server#172]
I use docker to build a clearml server on a device in the LAN. I can access the server through localhost:8080 port on the server device, but I cannot access it through ip:8080 on other devices in the LAN. How can I do this? Let other devices access the clearml server.

**Comment by jkhenning** [comment]
Hן @chakloong883 ,
This seems related to your network setup and not to the ClearML Server - I assume you have a firewall set up on the server machine blocking access to the 8080 port (and most likely to other ports as well). This might be `afw` if you're simply running on linux, or perhaps another firewall set up on your network.

**Comment by chakloong883** [comment]
> 

Thank you, It turns out that there is a problem with my port forwarding, I have solved the problem.

**Comment by chakloong883** [comment]
> Hi @chakloong883 , This seems related to your network setup and not to the ClearML Server - I assume you have a firewall set up on the server machine blocking access to the 8080 port (and most likely to other ports as well). This might be `afw` if you're simply running on linux, or perhaps another firewall set up on your network.

Thank you, It turns out that there is a problem with my port forwarding, I have solved the problem.
