### ISSUE TITLE
Change smoothing algorithm in scalar plots

### ISSUE THREAD

**Issue by pshvechikov** [allegroai/clearml-server#180]
Smoothing, in the limit of its parameter,  converges to a horizontal line at the value of the very first value (see image). 

I would expect smoothing to work as averaging. And extreme smoothing to result in the global average of all dots (not the value of the first dot). 

Is there a way to change the smoothing algorithm? Very important thing for me, as it is makes no sense to compare noisy metrics by their first values. And a lot of sense to compare by estimates of expected values. 

<img width="1597" alt="image" src="https://user-images.githubusercontent.com/3531361/218813405-62079e0c-4f1e-4715-8fee-8bfcfb68f841.png">

**Comment by pshvechikov** [comment]
[These lines](https://github.com/allegroai/clearml-web/blob/2b6aa6043c3f36e3349c6fe7235b77a3fddd0a09/src/app/webapp-common/shared/single-graph/single-graph.component.ts#L670-L677) seem to be related to the smoothing algo

**Comment by ainoam** [comment]
Thanks for highlighting the issue @pshvechikov.

We'll take a look at improving for a near release.

**Comment by pollfly** [comment]
Hey @pshvechikov! Just letting you know that this issue has been resolved in the recently released [v1.10](https://github.com/allegroai/clearml-server/releases/tag/v1.10). Let us know if there are any issues :)

**Comment by jkhenning** [comment]
@pshvechikov I'm closing the issue. Please reopen if required.
