### ISSUE TITLE
How can I find credentials from running server?

### ISSUE THREAD

**Issue by lambdaofgod** [allegroai/clearml-server#182]
I cannot start the server. I set some keys in CLEARML_API_ACCESS_KEY and CLEARML_API_SECRET_KEY and passed them in env file when running docker-compose, but when I go to web app after clearml-init I get "server unavailable" and see that there's some problem in the logs:
```
 Returned 400 for users.set_preferences in 8ms, msg=Invalid user id: id=869f81199c0a45269a0e51e0506d8ceb, company=d1bd92a3b039400cbafc60a7a5b1e52b
```
I also tried to remove ...KEY files from env file and the result is the same.

I made sure that there is no old config by deleting ~/clearml.conf and /opt/clearml.

How can I make sure that these keys match what's on the server?

My env file:
```
CLEARML_WEB_HOST="https://localhost:8082"
CLEARML_API_HOST="https://localhost:8008"
CLEARML_FILES_HOST="https://localhost:8081"
```

**Comment by ainoam** [comment]
@lambdaofgod ClearML access credentials are made available only once upon creation. 
If you are unsure whether you are holding correct credentials, you should use the UI to create a new set and use those.
