### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by hanship0530** [allegroai/clearml-server#184]
Hello
When I was trying to build clearml I got blow error

`[+] Building 37.4s (21/23)
 => [internal] load build definition from Dockerfile                                                                                                                                                                     0.0s
 => => transferring dockerfile: 1.34kB                                                                                                                                                                                   0.0s
 => [internal] load .dockerignore                                                                                                                                                                                        0.0s
 => => transferring context: 2B                                                                                                                                                                                          0.0s
 => [internal] load metadata for docker.io/library/centos:7                                                                                                                                                              0.2s
 => [internal] load build context                                                                                                                                                                                        0.0s
 => => transferring context: 17.55kB                                                                                                                                                                                     0.0s
 => CACHED [webapp 1/9] FROM docker.io/library/centos:7@sha256:be65f488b7764ad3638f236b7b515b3678369a5124c47b8d32916d6487418ea4                                                                                          0.0s
 => => resolve docker.io/library/centos:7@sha256:be65f488b7764ad3638f236b7b515b3678369a5124c47b8d32916d6487418ea4                                                                                                        0.0s
 => [webapp 2/9] RUN yum install -y curl git                                                                                                                                                                            19.9s
 => CACHED [staging_image 2/4] COPY --chmod=744 docker/build/internal_files/entrypoint.sh /opt/clearml/                                                                                                                  0.0s
 => CACHED [staging_image 3/4] COPY fileserver /opt/clearml/fileserver/                                                                                                                                                  0.0s
 => CACHED [staging_image 4/4] COPY apiserver /opt/clearml/apiserver/                                                                                                                                                    0.0s
 => CACHED [stage-2 2/8] COPY --from=staging_image /opt/clearml/ /opt/clearml/                                                                                                                                           0.0s
 => CACHED [stage-2 3/8] COPY --chmod=744 docker/build/internal_files/final_image_preparation.sh /tmp/internal_files/                                                                                                    0.0s
 => CACHED [stage-2 4/8] COPY docker/build/internal_files/clearml.conf.template /tmp/internal_files/                                                                                                                     0.0s
 => CACHED [stage-2 5/8] COPY docker/build/internal_files/clearml_subpath.conf.template /tmp/internal_files/                                                                                                             0.0s
 => CANCELED [stage-2 6/8] RUN /bin/bash -c '/tmp/internal_files/final_image_preparation.sh'                                                                                                                            37.1s
 => [webapp 3/9] RUN curl -fsSL https://rpm.nodesource.com/setup_16.x | bash -                                                                                                                                           2.3s
 => [webapp 4/9] RUN yum install -y nodejs                                                                                                                                                                               5.8s
 => [webapp 5/9] WORKDIR /opt                                                                                                                                                                                            0.0s
 => [webapp 6/9] RUN git clone https://github.com/allegroai/clearml-web.git clearml-web                                                                                                                                  1.9s
 => [webapp 7/9] RUN mv clearml-web /opt/open-webapp                                                                                                                                                                     4.1s
 => [webapp 8/9] COPY --chmod=744 docker/build/internal_files/build_webapp.sh /tmp/internal_files/                                                                                                                       0.0s
 => ERROR [webapp 9/9] RUN /bin/bash -c '/tmp/internal_files/build_webapp.sh'                                                                                                                                            2.9s
 > [webapp 9/9] RUN /bin/bash -c '/tmp/internal_files/build_webapp.sh':
#21 0.579 + set -e
#21 0.579 + cd /opt/open-webapp/
#21 0.579 + npm ci --unsafe-perm node-sass
#21 2.805 npm notice
#21 2.805 npm notice New major version of npm available! 8.19.3 -> 9.6.0
#21 2.805 npm notice Changelog: <https://github.com/npm/cli/releases/tag/v9.6.0>
#21 2.805 npm notice Run `npm install -g npm@9.6.0` to update!
#21 2.805 npm notice
#21 2.807 npm ERR! code ERESOLVE
#21 2.809 npm ERR! ERESOLVE could not resolve
#21 2.809 npm ERR!
#21 2.809 npm ERR! While resolving: @ngneat/dag@2.0.0
#21 2.809 npm ERR! Found: @angular/platform-browser-dynamic@14.2.12
#21 2.809 npm ERR! node_modules/@angular/platform-browser-dynamic
#21 2.809 npm ERR!   @angular/platform-browser-dynamic@"^14.2.12" from the root project
#21 2.809 npm ERR!   peer @angular/platform-browser-dynamic@"14.2.12" from @angular/platform-server@14.2.12
#21 2.809 npm ERR!   node_modules/@angular/platform-server
#21 2.809 npm ERR!     @angular/platform-server@"^14.2.12" from the root project
#21 2.810 npm ERR!
#21 2.810 npm ERR! Could not resolve dependency:
#21 2.810 npm ERR! peer @angular/platform-browser-dynamic@"13.3.5" from @ngneat/dag@2.0.0
#21 2.810 npm ERR! node_modules/@ngneat/dag
#21 2.810 npm ERR!   @ngneat/dag@"^2.0.0" from the root project
#21 2.810 npm ERR!
#21 2.810 npm ERR! Conflicting peer dependency: @angular/platform-browser-dynamic@13.3.5
#21 2.810 npm ERR! node_modules/@angular/platform-browser-dynamic
#21 2.810 npm ERR!   peer @angular/platform-browser-dynamic@"13.3.5" from @ngneat/dag@2.0.0
#21 2.810 npm ERR!   node_modules/@ngneat/dag
#21 2.810 npm ERR!     @ngneat/dag@"^2.0.0" from the root project
#21 2.810 npm ERR!
#21 2.810 npm ERR! Fix the upstream dependency conflict, or retry
#21 2.810 npm ERR! this command with --force, or --legacy-peer-deps
#21 2.810 npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
#21 2.810 npm ERR!
#21 2.810 npm ERR! See /root/.npm/eresolve-report.txt for a full report.
#21 2.811
#21 2.812 npm ERR! A complete log of this run can be found in:
#21 2.812 npm ERR!     /root/.npm/_logs/2023-03-03T03_33_01_857Z-debug-0.log
------
executor failed running [/bin/sh -c /bin/bash -c '/tmp/internal_files/build_webapp.sh']: exit code: 1`

my build command is 
`DOCKER_BUILDKIT=1 docker build --rm -t clearml-custom:0.1 -f docker/build/Dockerfile .`

I was tried to upgrade nodejs version 12 to 16 but it's not worked

Please give me advice.
Thanks

**Comment by shyallegro** [comment]
Hi @hanship0530 looks like we are pulling a more up to date node version then we expected
we need to update npm install command in the build script  to
`npm ci --legacy-peer-deps`
