### ISSUE TITLE
Can't access server deployed with AWS EC2 AMI

### ISSUE THREAD

**Issue by Arnechos** [allegroai/clearml-server#186]
Hello,

Today I deployed as a test EC2 instance using the follow AMI `ami-0261f8472a58ec706`, during deployment I had specified recommended instance size, created new security group with allowed access to public net. However I can't establish any connection to the web app using this url `http://<Public DNS (IPv4)>:8080`. Is there something else I should change in the AWS EC2 configuration?

**Comment by d13g0** [comment]
Can you comment on how you resolved the issue? I follow the instructions here:
https://clear.ml/docs/latest/docs/deploying_clearml/clearml_server_aws_ec2_ami/

For us-east-2 : ami-0c9e125de514df0b3 and had the same problem. 

Thanks!

**Comment by jkhenning** [comment]
In general, you need to make sure there are no security setting preventing you from reaching the instance. By default, an instance started on an AWS account with no special security group settings should be accessible from its public IP
