### ISSUE TITLE
Clearml-init: `Warning! Could not parse host name` forces pasting file address manually

### ISSUE THREAD

**Issue by pktiuk** [allegroai/clearml-server#198]
When I try to initialize clearml with `clearml-init` I get warning

```
pawel@mypc:~$ clearml-init
ClearML SDK setup process

Please create new clearml credentials through the settings page in your `clearml-server` web app (e.g. http://localhost:8080//settings/workspace-configuration) 
Or create a free account at https://app.clear.ml/settings/workspace-configuration

In settings page, press "Create new credentials", then press "Copy to clipboard".

Paste copied configuration here:
api { 
    web_server: https://clearml.xyz.local
    api_server: https://clearml.xyz.local:8008
    credentials {
        "access_key" = "91NIXSZGCETCCDH6SVHL"
        "secret_key"  = "MLAIC8SQMinkuY5FuGRrTGKavwSJP65XqNW9JFsZzgBRijic4G"
    }
}
Detected credentials key="91NIXSZGCETCCDH6SVHL" secret="MLAI***"
Warning! Could not parse host name
Files configured to: 
```
And then I have to manually paste my files address: `https://clearml.xyz.local:8081/`

I deployed ClearML on my local Linux machine with NGINX to add HTTPS.

**Comment by pktiuk** [comment]
I am not sure whether this issue should be in this repo or in https://github.com/allegroai/clearml

**Comment by jkhenning** [comment]
@pktiuk this seems to be the correct place 🙂 

Just to make sure, the UI is served under `https://clearml.xyz.local` in your case?

**Comment by jkhenning** [comment]
In general, the clearml-init auto-detection code is designed to use either http with ports or https with subdomains. Since in your case it's https with a port, the code simply does not know how to construct it from web/api addresses in the input provided

**Comment by pktiuk** [comment]
I will soon submit a PR handling this case.
