### ISSUE TITLE
Many CVEs in clearml:1.12.1

### ISSUE THREAD

**Issue by awoimbee** [allegroai/clearml-server#211]
A Trivy scan on docker.io/allegroai/clearml:1.11.0-373 returns more than 4000 lines of CVEs, some dating back from 2017.

Please upgrade your dependencies and make a release with security fixes.

**Comment by jkhenning** [comment]
Hi @awoimbee, 

We will soon be releasing a new updated docker image (for the next version)

**Comment by awoimbee** [comment]
`trivy image allegroai/clearml:1.12.1` still shows a lot of potential security issues, some very old and some critical.
I would not trust clearml (self-hosted or the paid hosted solution) to keep my data safe.

**Comment by awoimbee** [comment]
The fix in my case was to stop using clearml.
