### ISSUE TITLE
Failed Navigate From Overview to Experiments Details

### ISSUE THREAD

**Issue by muhammadAgfian96** [allegroai/clearml-server#228]
Hi, it seems new version of clearml failed to navigate when click point data from Overview Metrcis page. its Failed to fetch. Here i provied some information.

![image](https://github.com/allegroai/clearml-server/assets/43182086/38d1967c-668c-45ed-81ca-2c447b2c1f32)
![image](https://github.com/allegroai/clearml-server/assets/43182086/e82f0caf-8e52-4f2f-9680-753bf25eb6e9)
<img width="788" alt="Screenshot 2024-01-20 at 13 07 49" src="https://github.com/allegroai/clearml-server/assets/43182086/320b96e2-f53b-4e20-abdd-a556d2f563ca">
<img width="895" alt="Screenshot 2024-01-20 at 13 08 27" src="https://github.com/allegroai/clearml-server/assets/43182086/2d1d9170-90d1-443c-8d37-82ff21fcdf2b">

i use Self Hosting ClearML: WebApp: 1.14.0-431 • Server: 1.14.0-431 • API: 2.28

Thanks in advance!

**Comment by jkhenning** [comment]
Hi @muhammadAgfian96, thanks for this report, we will look at this asap

**Comment by evg-allegro** [comment]
Hi @muhammadAgfian96 , can you please share the contents of the "Payload" tab?

**Comment by muhammadAgfian96** [comment]
![Screenshot 2024-01-24 at 19 49 53](https://github.com/allegroai/clearml-server/assets/43182086/52165670-9d93-42e2-a9e7-cffe1153db35)
hi @evg-allegro , this one

**Comment by pollfly** [comment]
Hey @muhammadAgfian96 ! Just letting you know that this issue has been resolved in [v1.14.1](https://github.com/allegroai/clearml-server/releases/tag/v1.14.1). Let us know if there are any issues :)
