### ISSUE TITLE
Scalar graphs legend is too narrow for experiments with long names

### ISSUE THREAD

**Issue by H4dr1en** [allegroai/clearml-server#241]
Pretty much the title, here is how it looks like in clearml-server 1.14:

**In the scalar graph view**
This is the scalar graph when comparing two experiments with long names. The long names take 50% of the vertical space of the graph
<img width="326" alt="Screenshot 2024-04-15 at 15 34 23" src="https://github.com/allegroai/clearml-server/assets/16240134/5f32f13f-1ef5-424e-8ac7-9dc1ea14dd2d">

A solution to fix this would be stack the legend horizontally (not vertically) and allow 100% of the width of the graph for the legend

**In the extended scalar graph view**
This is the extended scalar graph when comparing two experiments with long names. Here the issue is that it is impossible to read the value for both experiments because the tooltip created on hover has a too narrow width
<img width="149" alt="Screenshot 2024-04-15 at 15 34 53" src="https://github.com/allegroai/clearml-server/assets/16240134/796b803b-3afc-4cc6-90d3-426533b41a97">

A solution to fix this would be to 5x the width of the tooltip showing the scores

**Comment by ainoam** [comment]
@H4dr1en v1.15 significantly improves scalar legend and tooltip behaviour.

**Comment by H4dr1en** [comment]
Thank you, will update and have a look 👍

**Comment by H4dr1en** [comment]
Hi @ainoam , I updated to v1.15 and I still have exactly the same layouts, the issue is still there

**Comment by ainoam** [comment]
Thanks for letting us know @H4dr1en. We'll take a look.

**Comment by H4dr1en** [comment]
@ainoam There might be an issue with the docker image because I did pull the last version (1.15) of the server but I see in the web interface: `WebApp: 1.14.1-451 • Server: 1.15.0-472 • API: 2.29` -> the web app is not updated

**Comment by H4dr1en** [comment]
@ainoam nevermind I fix this, so I do have the last web interface as well now `WebApp: 1.15.0-472 • Server: 1.15.0-472 • API: 2.29` but the issue still exists

**Comment by ainoam** [comment]
Thanks for the updates @H4dr1en. We'll update as more information becomes available.

**Comment by pollfly** [comment]
Hey @H4dr1en! Just letting you know that this issue has been resolved in the recently released [v1.16.0](https://github.com/allegroai/clearml-server/releases/tag/v1.16.0). Let us know if there are any issues :)

**Comment by H4dr1en** [comment]
Very nice @pollfly , I'll close it for now, update in the following days and will reopen if the issue is still there 👍
