### ISSUE TITLE
default_worker_timeout_sec is ignored

### ISSUE THREAD

**Issue by H4dr1en** [allegroai/clearml-server#251]
Pretty much the title - I am setting this setting to 60 so that when an ec2 instance hosting an agent is killed by the autoscaler, its agent is deregistered after only 60 seconds - but this setting has not effect and the default value of 10 minutes is still in use

I set the value to 60 in `/opt/clearml/config/services.conf`:
```
default_worker_timeout_sec: 60
```
and restarted the server with `docker-compose restart`

**Comment by evg-allegro** [comment]
@H4dr1en Inside services.conf do you put it under workers section? 
`
workers {
  default_worker_timeout_sec: 60
}
`

**Comment by H4dr1en** [comment]
Ho my bad, and it's actually well documented in the note [here](https://clear.ml/docs/latest/docs/deploying_clearml/clearml_server_config/#configuration-files), I someone missed it, thanks!
