### ISSUE TITLE
`Clear` button

### ISSUE THREAD

**Issue by iakremnev** [allegroai/clearml-server#42]
## Feature request

Hi! I would love to see a `clear` UI button next to the `edit` button to easily clear the installed python package list before enqueuing an experiment.

![Screenshot from 2020-06-01 11-32-48](https://user-images.githubusercontent.com/13620282/83395916-ca0e1880-a403-11ea-8845-1b275253c2b7.png)

### Use case

I install forked packages with Docker with a
```
git+git://github.com/MyPublicRepo/albumentations@master#egg=albumentations
git+https://${GITHUB_TOKEN}:@github.com/MySecretRepo/numpy@master#egg=numpy
```
line in `requirements.txt`. If I don't clear the package list, trains-agent will install the official package from pypi. Right now I click `edit`, select all packages and clear them manually. Not much effort but could be better :)

### Alternative solution

Add source url for packages installed not from pypi. Like the exact github link.

**Comment by bmartinn** [comment]
@iakremnev thank you for the idea
This is great, and so trivial we should definitely have it :)
v0.15 was just released, but I believe we will add it to the next version :)
