### ISSUE TITLE
[BUG] failure fetching logs

### ISSUE THREAD

**Issue by amito** [allegroai/clearml-server#59]
Hey,

We have Trains server locally deployed on our AWS server. I deployed the instance following [the instructions](https://allegro.ai/docs/deploying_trains/trains_deploy_overview/), using the latest community AMI (allegroai-trains-server-0.16.0-299-259 (ami-06017d314ea702a02)).

After running an experiment from one of our machines, when I go into experiment results --> log page, I get an "*Failed to fetch log*" error modal.
Inspecting the traffic shows a *500 HTTP response* from `events.get_task_log` with *an extremely detailed traceback* (*) from the Python backend.
The error seems to be pinned at a `KeyError` in line 103 in the file `server/bll/event/log_events_iterator.py`, in the `_get_events` method, when trying to address `ev['_id']`.

The full JSON response (and the encapsulated traceback):
```
{
    "meta":{
        "id":"88d37362c83144f49d285a2feecf518d",
        "trx":"88d37362c83144f49d285a2feecf518d",
        "endpoint":{
            "name":"events.get_task_log",
            "requested_version":"2.9",
            "actual_version":"2.9"
        },
        "result_code":500,
        "result_subcode":0,
        "result_msg":"'_id'",
        "error_stack":"Traceback (most recent call last):\n  File \"/opt/trains/server/service_repo/service_repo.py\", line 255, in handle_call\n    ret = endpoint.func(call, company, call.data_model)\n  File \"/opt/trains/server/services/events.py\", line 114, in get_task_log\n    from_timestamp=request.from_timestamp,\n  File \"/opt/trains/server/bll/event/log_events_iterator.py\", line 42, in get_task_events\n    from_timestamp=from_timestamp,\n  File \"/opt/trains/server/bll/event/log_events_iterator.py\", line 103, in _get_events\n    already_present_ids = set(ev[\"_id\"] for ev in events)\n  File \"/opt/trains/server/bll/event/log_events_iterator.py\", line 103, in <genexpr>\n    already_present_ids = set(ev[\"_id\"] for ev in events)\nKeyError: '_id'\n"
    },
    "data":{

    }
}
```

(*) Doesn't seem like a good idea sending the full backend traceback in the HTTP response...

Thanks

**Comment by jkhenning** [comment]
Hi @amito ,

This seems to be some race condition in the server - we're checking it now and will probably fix and release a patch version soon.

**Comment by amito** [comment]
Hi,

Any news on this one?

Thanks.

**Comment by jkhenning** [comment]
Hi @amito,

Sorry, forgot to update, the new Trains Server release v0.16.1 should solve this issue.

**Comment by amito** [comment]
Thanks @jkhenning.
Where can I find the release notes and changelog for this new version, and the docs covering the upgrade process?

**Comment by jkhenning** [comment]
https://github.com/allegroai/trains-server/releases/tag/0.16.1
https://allegro.ai/docs see "Deploying Trains/Deploying Trains Server/<your platform>/Upgrading"
