### ISSUE TITLE
UI improvement suggestions

### ISSUE THREAD

**Issue by uriariel** [allegroai/clearml-server#61]
Please consider adding the following features:
UI:
1. selecting a range of objects using held down shift.
2. removing experiments and models and not just archiving.

**Comment by ainoam** [comment]
@uriariel May I suggest posting this suggestion under https://github.com/allegroai/trains/issues/81 , this is where we try to collect all the UI suggestions from users, and slowly but surely add them into Trains :)

Until the UI supports experiment removal - Take a look at https://github.com/allegroai/trains-server/issues/53#issuecomment-660667572 to keep you projects in order :)

**Comment by ainoam** [comment]
Belated closure: (1) has been added back in [v0.17](https://github.com/allegroai/clearml-server/releases/tag/0.17.0), and (2) in [v1.0](https://github.com/allegroai/clearml-server/releases/tag/1.0.0).
