### ISSUE TITLE
[UI] Hyper parameters do not show up when category name starts with "#" 

### ISSUE THREAD

**Issue by n-Guard** [allegroai/clearml-server#79]
I upgraded to clearml-server v1.0.2 and recently noticed that I cannot display or edit hyper parameters in the CONFIGURATION tab when the category starts with the hashtag symbol (e.g. #hparams).
When I click on this category it is not highlighted like other categories (e.g. Args) and nothing is displayed, I tried with Chrome, Firefox and Safari on macOS.
Programmatically retrieving the category with its content is no problem though.

**Comment by oren-allegro** [comment]
@n-Guard - thanks for reporting. I managed to reproduce and will try to fix for the next release.
