### ISSUE TITLE
Self Hosted ClearMl Server - No option to create credentials

### ISSUE THREAD

**Issue by okyspace** [allegroai/clearml-server#81]
Hi, I deployed my clearml server with image v1.1.1 in kubernetes.
All pods (redis, mongo, elastic, file, api, web servers) are running without error. 
However when I access my webserver, I do not have option to create credential. 
![image](https://user-images.githubusercontent.com/55354225/128829586-93ad4779-c207-4872-a3ea-b2f6c8ae431c.png)

From my browser network, I got http400 for these api calls. 
![image](https://user-images.githubusercontent.com/55354225/128829913-a12edd16-7012-47f0-b0d7-b09846ddbe75.png)
I don't seems to be able to locate the issue. Any advice?

**Comment by okyspace** [comment]
Resolved. As pointed out by experts in slack channel, the issue is due to dirty cookies. 
Either you test with a incogn browser or you can do app.clearml.domain/login to successfully login. This might happened if we tried too many installations.

**Comment by bmartinn** [comment]
Thanks @okyspace for updating here on the solution 👍
