### ISSUE TITLE
Migrate ClearML Server to a new domain

### ISSUE THREAD

**Issue by lamhoangtung** [allegroai/clearml-server#83]
We are trying to migrate a ClearML Server to a new domain by simply pointing the public IP address of the server to the new domain. Everything seems fine but all the DEBUG SAMPLE are unable to load. By inspecting the page, I saw that the server tried to get the images from the old domain

![Image Pasted at 2021-8-16 21-25](https://user-images.githubusercontent.com/26834698/129582476-49a649e3-78c6-4c08-aafe-a65253bf1213.png)

In this case, our new domain is: `clearml.xxx.com` and the old domain are `files.mlchain.ml`

Are there anything that we are missing here? If not, can you guys help us change the old domain to the new domain inside the DB manually ?

Thanks for checking by

**Comment by jkhenning** [comment]
Hi @lamhoangtung ,

You're quite right - the images are registered using the reporter URL (since they might be stored in various locations).

Making such a change would require a migration of the images using an explicit ES query to the elasticsearch service.

**Comment by lamhoangtung** [comment]
@jkhenning Can you gave us some instruction to do so ;-; ?

**Comment by lamhoangtung** [comment]
We edit the docker-compose file to expose port 9200 of the ElasticSearch service and use the following Python script to rename the domain:

```python
import logging
import os

import elasticsearch
from elasticsearch import RequestsHttpConnection

BASE_PATH = os.path.dirname(os.path.abspath(__file__))

logging.basicConfig()
logging.root.setLevel(logging.INFO)
logger = logging.getLogger("fix_ekyc")


INDEX_URL = "http://localhost:9200"

ES_CLIENT = elasticsearch.Elasticsearch(hosts=INDEX_URL, verify_certs=False, ca_certs=False,
                                        connection_class=RequestsHttpConnection, timeout=3000, max_retries=10)

# Use https://elasticvue.com to find the index
index = "events-training_debug_image-<....>"

q = {
    "script": {
        "source": "ctx._source.url = ctx._source.url.replace('https://files.<OLD_DOMAIN>', 'https://files.<NEW_DOMAIN>')",
        "lang": "painless"
    },
    "query": {
        "match_all": {}
    }
}

ES_CLIENT.update_by_query(body=q, index=index)
```

To find the correct index, we used Elasticvue GUI, it should be something like: `events-training_debug_image-xxxxx`

Problem solved.

**Comment by jkhenning** [comment]
Hi @lamhoangtung,

Good job - you beat me to it 😄

**Comment by korotaS** [comment]
For those wondering how to fix this in newer versions (I suppose the newer versions of ClearML could have changed files api a bit):
In @lamhoangtung 's solution (thank you for it btw!) I changed this line 
```python
"source": "ctx._source.url = ctx._source.url.replace('https://files.<OLD_DOMAIN>', 'https://files.<NEW_DOMAIN>')",
```
to this:
```python
"source": "ctx._source.url = ctx._source.url.replace('<OLD_DOMAIN>', '<NEW_DOMAIN>')",
```
And it worked for me. 
Also, instead of using https://elasticvue.com, you can use just
```shell
curl http://localhost:9200/_aliases?pretty=true | grep debug
```
And find `events-training_debug_image-xxxxx` there.

My versions: WebApp: 1.9.2-317 • Server: 1.9.2-317 • API: 2.23

**Comment by sriram-dsl** [comment]
Certainly! Here's a corrected version of your text:

"I am running a ClearML self-hosting server locally on ports 8080, 8081, and 8008. I want to access the server from a remote machine. I attempted port forwarding and tried to access it, but the dynamic IP is causing an issue. Can anyone tell me how to configure the ClearML server with a public IP?"
