### ISSUE TITLE
[Feature Request] Custom nodeSelector and anti-affinity for all pods

### ISSUE THREAD

**Issue by stefano-cherchi** [allegroai/clearml-server#94]
Currently, when deploying ClearML with Helm, there is a single `nodeSelector` attribute in the main `clearml:` block. This parameter is propagated to all the ClearML services: apiserver, webserver, elasticsearch etc. The clearml-agents, on the other hand, have no way to specify a selector.

It would be very useful to configure node selectors and anti-affinities on each service in the values file. 

For example, I'd like to be sure that no more than one clearml-agent is running on each node of the cluster. I'd also like to be able to schedule the mongo pod an on-demand instance while keeping stateless services on a spot instance, etc.

EDIT: moved to the appropriate project: https://github.com/allegroai/clearml-helm-charts/issues/35

**Comment by jkhenning** [comment]
@stefano-cherchi can you please open this issue in the https://github.com/allegroai/clearml-helm-charts repository?

**Comment by stefano-cherchi** [comment]
> @stefano-cherchi can you please open this issue in the https://github.com/allegroai/clearml-helm-charts repository?

Hi Jake, of course. Sorry for the inconvenience.

**Comment by jkhenning** [comment]
No worries 🙂 

Thanks! Closing this issue as I see you already opened it there 👍
