### ISSUE TITLE
Auto scaling agents

### ISSUE THREAD

**Issue by Mokto** [allegroai/clearml-server#95]
Hi,

I'm using Kubernetes & defined multiple agents per queue.
To reduce costs I'd like to do autoscaling on those. From 0 to n based on the number of pending jobs.

Even though it might not be in the scope of the project, I'm looking at a way of checking the the queue size properly.
Right all I see is using :

Task.get_all with status='queued'. Any other idea?

Thanks.

**Comment by jkhenning** [comment]
Hi @Mokto,

Are you using the ClearML SDK?

Currently the ClearML API will allow you to get the entire queue contents using `queues.get_all` (or `queues.get_by_id` if you know the queue's ID). You can use the APIClient for that, as follows:

```python
from clearml.backend_api.session.client import APIClient
client = APIClient()

queues = client.queues.get_all()

for queue in queues:
    print(f"Queue {queue.name} ({queue.id}) has {len(queue.entries)} pending tasks")
```

It's not ideal in terms of performance (since you're pulling all the queues with all of the task entries), but unless you have thousands of pending tasks, it should be fine 🙂

**Comment by Mokto** [comment]
Thanks, that helps a lot!

**Comment by Mokto** [comment]
Just tried your solution!

Unfortunately queue.entries only contains the pending tasks, not the running ones from that same queue. 

So the flow is like this:
1. I push a task in the queue
2. My watcher detects an element in queue.entries and scales up
3. A new agent spins and move the task from pending to running
4. My watcher sees 0 pending tasks and scales down, even if the running task is not completed.

**Comment by jkhenning** [comment]
Hi @Mokto,

Well, that's true - tasks are pulled out of the queue. If you want to count tasks that are still running but have originated from the queue, you can simply query on them. However, currently you can't use the `APIClient` to query tasks using their origin queue ID - that's possible only using the REST API

**Comment by Mokto** [comment]
Do you happen to have Swagger/OpenAPI somewhere. Or point me out how to use the API properly ?

I think it would be useful too many people.

Thanks!

**Comment by jkhenning** [comment]
The API documentation is here: https://clear.ml/docs/latest/docs/references/api/index

We're still missing the authentication introduction, but in a nutshell, you can use basic auth as follows:

```python
import requests
from requests.auth import HTTPBasicAuth

key = "<credential key for the user>"
secret = "<credential secret for the user>"

url = 'http://<hostname>:8008/<endpoint>'
res = requests.post(url, auth=HTTPBasicAuth(key, secret), json=<json body>)
```

**Comment by Mokto** [comment]
I got it working thanks.

For anyone having the same need, here is how I did it:

```
    res = requests.post(
        "https://YOURENDPOINT/tasks.get_all",
        auth=HTTPBasicAuth(
            "XXX", "YYYY"
        ),
        json={
            "status": ["queued", "in_progress"],
            "only_fields": ["name", "execution", "id", "status"],
        },
    )
    body = json.loads(res.content)
    tasks = body["data"]["tasks"]

    for task in tasks:
        if "execution" in task:  # run by an agent
            queue_id = task["execution"]["queue"]
```

**Comment by Mokto** [comment]
Good point, thanks! I'm working on multiple queues at the same times though. But you code is better for a single queue.
